version: '3'

volumes:
  mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8
    container_name: syonet_mysql
    ports:
      - 3306:3306
    env_file:
      - ../../.env.development.local
    environment:
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
